### PR TITLE
fix: BREAKING CHANGE: timeout is per imap action instead of overall for polling interval

### PR DESCRIPTION
**Pull request by lucidNTR**
…ing interval

use lodash.once instead of function override, allow exclusion of successful emails from a previous unsuccessful polling interval

@jo @gr2m @tlvince @lucychambers

### CODE REVIEW

**Comment by tlvince** [comment]
Could you reformat the initial commit's message to include `BREAKING CHANGE:` in the footer, per [conventional-changelog](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md)?

**Comment by lucidNTR** [comment]
sure

**Comment by tlvince** [comment]
There needs to be a blank line before `BREAKING CHANGE`, e.g.:

```
fix: use lodash.once instead of function override, allow exclusion of successful emails from a previous unsuccessful polling interval

BREAKING CHANGE: timeout is per imap action instead of overall for polling interval
```

(Sorry).

**Comment by lucidNTR** [comment]
@tlvince @jo fixed commit message and included dirty overquota handling + bug fix of failing timeout

**Comment by tlvince** [comment]
LGTM.

**Pull request merged**
